version: "{build}"
skip_tags: true
clone_folder: c:\gopath\src\github.com\Aiicy\AiicyDS
clone_depth: 1

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.7

build: false
deploy: false

before_install:
   - go get -v -t -d

install:
  - go build -v

notifications:
  - provider: Email
    to:
      - admin@aiicy.com
    on_build_success: false
