version: "{build}"
skip_tags: true
clone_folder: c:\gopath\src\github.com\Aiicy\AiicyDS
clone_depth: 1

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.7

deploy: false

build_script:
  - go get -v -t -d 

install:
  - go get -v -t -d 
  
configuration:
  - Debug
  - Release

notifications:
  - provider: Email
    to:
      - admin@aiicy.com
    on_build_success: false
